title: Can Zhang
position: Ph.D. Student
affiliation: SOC, NUS
email: can.zhang (at) u.nus.edu
keywords: Computer Vision (CV), Machine Learning (ML)
google_scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&tzom=-480&user=L5FqsN4AAAAJ
github_link: https://github.com/lulusindazc
#cv_link: https://drive.google.com/file/d/13Um-es_1eork88GVa3JvtxG7UMcWN8MV/view?usp=sharing
linkedin: https://www.linkedin.com/in/can-zhang-985889264/
avatar: ./assets/img/zc.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/smile_favicon.png
favicon_dark: ./assets/img/smile_favicon.png
description: Can's blog
canonical: https://lulusindazc.github.io/can-zhang/
remote_theme: lulusindazc/can-zhang
